export default [
    {
        name: 'franchisee',
        alias: [
            {
                id: 1,
                name: 'Franchisee1',
                for_user: [
                    'Velda',
                    'Josephine',
                    'Herman',
                    'Lorenz',
                    'Alanis',
                    'Karli',
                    'Rosalyn',
                    'Elliot',
                ],
            },
            {
                id: 2,
                name: 'Franchisee2',
                for_user: [
                    'Ashlee',
                    'Kristy',
                    'Shannon',
                    'Ada',
                    'Taylor',
                    'Maeve',
                    'Coby',
                    'Patsy',
                    'Gayle',
                    'Larry',
                    'Lou',
                ],
            },
            {
                id: 3,
                name: 'Franchisee3',
                for_user: [
                    'Ward',
                    'Vince',
                    'Ashlynn',
                    'Haylie',
                    'May',
                    'Katrine',
                ],
            },
            {
                id: 4,
                name: 'Franchisee4',
                for_user: [
                    'Ashlee',
                    'Kristy',
                    'Shannon',
                    'Ada',
                    'Taylor',
                    'Maeve',
                ],
            },
            {
                id: 5,
                name: 'Franchisee5',
                for_user: ['Sage', 'Ansel', 'Zita'],
            },
            {
                id: 6,
                name: 'Franchisee6',
                for_user: [
                    'Sierra',
                    'Lazaro',
                    'Magdalen',
                    'Clifford',
                    'Markus',
                    'Hadley',
                    'Morton',
                    'Mallie',
                    'Verdie',
                    'Mortimer',
                    'Reymundo',
                    'Cathrine',
                    'Kaia',
                    'Jazmin',
                    'Danielle',
                    'Sage',
                    'Ansel',
                    'Zita',
                    'Delores',
                    'Ezequiel',
                    'Raphael',
                    'Orval',
                    'Gregoria',
                    'Aylin',
                    'Elvera',
                    'Lon',
                    'Duncan',
                    'Ambrose',
                    'Luna',
                    'Urban',
                    'Pauline',
                    'Don',
                ],
            },
            {
                id: 7,
                name: 'Franchisee7',
                for_user: ['Nicolas', 'Lucius', 'Randy', 'Micaela', 'Arturo'],
            },
        ],
    },
    {
        name: 'site',
        alias: [
            {
                id: 1,
                name: 'Site1',
                for_user: ['User1', 'User2', 'User3', 'User4', 'User6'],
            },
            {
                id: 2,
                name: 'Site2',
                for_user: ['User1', 'User3', 'User4', 'User5', 'User6'],
            },
            {
                id: 3,
                name: 'Site3',
                for_user: ['User1', 'User2', 'User4', 'User5', 'User6'],
            },
            {
                id: 4,
                name: 'Site4',
                for_user: ['User1', 'User2', 'User4', 'User5', 'User6'],
            },
            {
                id: 5,
                name: 'Site5',
                for_user: ['User1', 'User2', 'User3', 'User5', 'User6'],
            },
            {
                id: 6,
                name: 'Site6',
                for_user: ['User1', 'User2', 'User3', 'User4', 'User5'],
            },
            {
                id: 7,
                name: 'Site7',
                for_user: ['User2', 'User3', 'User5', 'User6'],
            },
        ],
    },
]
