import { IScheduleData, ISurvey } from './pages/Survey'

function wait<T>(ms: number, value: T) {
    return new Promise<T>((resolve) => setTimeout(resolve, ms, value))
}

export const mockSchedule = async () => {
    const mockSchedules: IScheduleData[] = [
        {
            name: 'Documentation 1',
            start_date: '04-24-2023',
            show_over_due: true,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 2',
            start_date: '01-04-2023',
            show_over_due: false,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 3',
            start_date: '05-11-2023',
            show_over_due: true,
            sched_freq:
                'Repeats every 1 months(s), on day 1 of the month, end on 31 June, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 4',
            start_date: '04-24-2023',
            show_over_due: false,
            sched_freq: 'Repeats every 1 days, ends on 29 May, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 12',
            ],
        },
        {
            name: 'Documentation 5',
            start_date: '05-14-2023',
            show_over_due: false,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 6',
            start_date: '01-21-2023',
            show_over_due: true,
            sched_freq: 'Repeats every 1 days, ends on 29 May, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 7',
            start_date: '04-24-2023',
            show_over_due: true,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
            ],
        },
        {
            name: 'Documentation 8',
            start_date: '01-24-2023',
            show_over_due: false,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 9',
            start_date: '03-24-2023',
            show_over_due: true,
            sched_freq:
                'Repeats every 1 months(s), on day 1 of the month, end on 31 June, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 10',
            start_date: '04-24-2023',
            show_over_due: true,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 11',
            start_date: '01-24-2023',
            show_over_due: true,
            sched_freq:
                'Repeats every 1 months(s), on day 1 of the month, end on 31 June, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 12',
            start_date: '01-14-2023',
            show_over_due: false,
            sched_freq: 'Repeats every 1 week(s) on: Monday, Wednesday',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 13',
            start_date: '04-04-2023',
            show_over_due: true,
            sched_freq:
                'Repeats every 1 months(s), on day 1 of the month, end on 31 June, 2023',
            for_user: [
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Documentation 14',
            start_date: '04-24-2023',
            show_over_due: true,
            sched_freq: 'Repeats every 1 days, ends on 29 May, 2023',
            for_user: ['User 1'],
        },
        {
            name: 'Documentation 15',
            start_date: '04-21-2023',
            show_over_due: true,
            sched_freq:
                'Repeats every 1 months(s), on day 1 of the month, end on 31 June, 2023',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
    ]

    return await wait(3000, mockSchedules)
}

export const mockSurvey = async () => {
    const mockSchedules: ISurvey[] = [
        {
            name: 'Survey 1',
            expiry_date: '04-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '0KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 2',
            expiry_date: '01-04-2023',
            qr_image: 'https://picsum.photos/200',
            path: '1KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 3',
            expiry_date: '05-11-2023',
            qr_image: 'https://picsum.photos/200',
            path: '2KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 4',
            expiry_date: '04-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 12',
            ],
        },
        {
            name: 'Survey 5',
            expiry_date: '05-14-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 6',
            expiry_date: '01-21-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 7',
            expiry_date: '04-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
            ],
        },
        {
            name: 'Survey 8',
            expiry_date: '01-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 9',
            expiry_date: '03-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 10',
            expiry_date: '04-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 11',
            expiry_date: '01-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 12',
            expiry_date: '01-14-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 6',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 13',
            expiry_date: '04-04-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 4',
                'User 5',
                'User 6',
                'User 7',
                'User 8',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
        {
            name: 'Survey 14',
            expiry_date: '04-24-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: ['User 1'],
        },
        {
            name: 'Survey 15',
            expiry_date: '04-21-2023',
            qr_image: 'https://picsum.photos/200',
            path: '3KFNLztllSbTlXckrVE9Kx',
            for_user: [
                'User 1',
                'User 2',
                'User 3',
                'User 4',
                'User 5',
                'User 9',
                'User 10',
                'User 11',
                'User 12',
            ],
        },
    ]

    return await wait(3000, mockSchedules)
}
